import { Tool } from '@/types/database';

// Mock data for development and demo purposes
export const mockTools: Tool[] = [
  {
    id: '1',
    name: 'Mattermost',
    description: 'Open source platform for secure collaboration across the entire software development lifecycle.',
    github_url: 'https://github.com/mattermost/mattermost',
    saas_equivalent: 'Slack',
    category: 'Communication',
    stars: 28000,
    last_commit: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 4,
    docker_ready: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Plane',
    description: 'Open source project planning tool for tracking issues, epics, and product roadmaps.',
    github_url: 'https://github.com/makeplane/plane',
    saas_equivalent: 'Jira',
    category: 'Project Management',
    stars: 26000,
    last_commit: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 5,
    docker_ready: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Plausible',
    description: 'Simple, open source, lightweight and privacy-friendly web analytics alternative to Google Analytics.',
    github_url: 'https://github.com/plausible/analytics',
    saas_equivalent: 'Google Analytics',
    category: 'Analytics',
    stars: 19000,
    last_commit: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 3,
    docker_ready: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Twenty',
    description: 'Modern CRM offering the flexibility of open-source, advanced features, and a sleek design.',
    github_url: 'https://github.com/twentyhq/twenty',
    saas_equivalent: 'Salesforce',
    category: 'CRM',
    stars: 15000,
    last_commit: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 6,
    docker_ready: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Lago',
    description: 'Open source metering and usage-based billing platform for product-led SaaS.',
    github_url: 'https://github.com/getlago/lago',
    saas_equivalent: 'Stripe Billing',
    category: 'Finance',
    stars: 6500,
    last_commit: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 5,
    docker_ready: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Chatwoot',
    description: 'Open-source customer engagement suite, an alternative to Intercom, Zendesk, and Salesforce Service Cloud.',
    github_url: 'https://github.com/chatwoot/chatwoot',
    saas_equivalent: 'Intercom',
    category: 'Communication',
    stars: 20000,
    last_commit: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 4,
    docker_ready: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Listmonk',
    description: 'High performance, self-hosted, newsletter and mailing list manager with a modern dashboard.',
    github_url: 'https://github.com/knadh/listmonk',
    saas_equivalent: 'Mailchimp',
    category: 'Marketing',
    stars: 14000,
    last_commit: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 2,
    docker_ready: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Gitea',
    description: 'Painless self-hosted all-in-one software development service including Git hosting, code review, and CI/CD.',
    github_url: 'https://github.com/go-gitea/gitea',
    saas_equivalent: 'GitHub',
    category: 'DevTools',
    stars: 43000,
    last_commit: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 3,
    docker_ready: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'MinIO',
    description: 'High-performance, S3 compatible object storage. Built for AI/ML, data lakes, and high-performance applications.',
    github_url: 'https://github.com/minio/minio',
    saas_equivalent: 'AWS S3',
    category: 'Storage',
    stars: 45000,
    last_commit: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 4,
    docker_ready: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Vaultwarden',
    description: 'Unofficial Bitwarden compatible server written in Rust. Lightweight and perfect for self-hosting.',
    github_url: 'https://github.com/dani-garcia/vaultwarden',
    saas_equivalent: 'Bitwarden',
    category: 'Security',
    stars: 35000,
    last_commit: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 2,
    docker_ready: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'AFFiNE',
    description: 'The next-gen knowledge base that brings planning, sorting, and creating together. Privacy-focused and local-first.',
    github_url: 'https://github.com/toeverything/AFFiNE',
    saas_equivalent: 'Notion',
    category: 'Project Management',
    stars: 36000,
    last_commit: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 5,
    docker_ready: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Umami',
    description: 'Simple, fast, privacy-focused alternative to Google Analytics that respects visitor privacy.',
    github_url: 'https://github.com/umami-software/umami',
    saas_equivalent: 'Google Analytics',
    category: 'Analytics',
    stars: 21000,
    last_commit: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 2,
    docker_ready: true,
    created_at: new Date().toISOString(),
  },
];
