import { Tool } from '@/types/database';

// Mock data for development and demo purposes
export const mockTools: Tool[] = [
  {
    id: '1',
    name: 'Mattermost',
    description: 'Open source platform for secure collaboration across the entire software development lifecycle.',
    github_url: 'https://github.com/mattermost/mattermost',
    saas_equivalent: 'Slack',
    category: 'Communication',
    stars: 28000,
    last_commit: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 4,
    docker_ready: true,
    created_at: new Date().toISOString(),
    // v2 fields
    license_type: 'MIT',
    fork_count: 5600,
    top_contributors: ['mattermost-build:2500', 'jwilander:1800', 'hmhealey:1200', 'crspeller:950'],
    languages: ['Go:850000', 'TypeScript:420000', 'JavaScript:180000', 'HTML:50000'],
  },
  {
    id: '2',
    name: 'Plane',
    description: 'Open source project planning tool for tracking issues, epics, and product roadmaps.',
    github_url: 'https://github.com/makeplane/plane',
    saas_equivalent: 'Jira',
    category: 'Project Management',
    stars: 26000,
    last_commit: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 5,
    docker_ready: true,
    created_at: new Date().toISOString(),
    // v2 fields
    license_type: 'AGPL-3.0',
    fork_count: 5200,
    top_contributors: ['pramitgaha:1650', 'aaryan610:1420', 'NarayanBavisetti:980'],
    languages: ['TypeScript:720000', 'Python:280000', 'JavaScript:95000', 'CSS:45000'],
  },
  {
    id: '3',
    name: 'Plausible',
    description: 'Simple, open source, lightweight and privacy-friendly web analytics alternative to Google Analytics.',
    github_url: 'https://github.com/plausible/analytics',
    saas_equivalent: 'Google Analytics',
    category: 'Analytics',
    stars: 19000,
    last_commit: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 3,
    docker_ready: true,
    created_at: new Date().toISOString(),
    // v2 fields
    license_type: 'AGPL-3.0',
    fork_count: 3800,
    top_contributors: ['ukutaht:3200', 'metmarkosaric:820', 'RobertJoonas:540'],
    languages: ['JavaScript:380000', 'Elixir:320000', 'HTML:65000', 'CSS:28000'],
  },
  {
    id: '4',
    name: 'Twenty',
    description: 'Modern CRM offering the flexibility of open-source, advanced features, and a sleek design.',
    github_url: 'https://github.com/twentyhq/twenty',
    saas_equivalent: 'Salesforce',
    category: 'CRM',
    stars: 15000,
    last_commit: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 6,
    docker_ready: true,
    created_at: new Date().toISOString(),
    // v2 fields
    license_type: 'AGPL-3.0',
    fork_count: 3000,
    top_contributors: ['charlesBochet:4800', 'FelixMalfait:2100', 'Weiko:1650'],
    languages: ['TypeScript:890000', 'JavaScript:42000', 'CSS:28000'],
  },
  {
    id: '5',
    name: 'Lago',
    description: 'Open source metering and usage-based billing platform for product-led SaaS.',
    github_url: 'https://github.com/getlago/lago',
    saas_equivalent: 'Stripe Billing',
    category: 'Finance',
    stars: 6500,
    last_commit: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 5,
    docker_ready: true,
    created_at: new Date().toISOString(),
    // v2 fields
    license_type: 'AGPL-3.0',
    fork_count: 1300,
    top_contributors: ['lovrosdusko:1850', 'ancorcruz:1240', 'josephjz:680'],
    languages: ['Ruby:540000', 'TypeScript:180000', 'JavaScript:92000', 'HTML:35000'],
  },
  {
    id: '6',
    name: 'Chatwoot',
    description: 'Open-source customer engagement suite, an alternative to Intercom, Zendesk, and Salesforce Service Cloud.',
    github_url: 'https://github.com/chatwoot/chatwoot',
    saas_equivalent: 'Intercom',
    category: 'Communication',
    stars: 20000,
    last_commit: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 4,
    docker_ready: true,
    created_at: new Date().toISOString(),
    // v2 fields
    license_type: 'MIT',
    fork_count: 4000,
    top_contributors: ['sojan-official:2800', 'pranavrajs:1950', 'nithindavid:1100'],
    languages: ['Ruby:620000', 'Vue:380000', 'JavaScript:140000', 'HTML:45000'],
  },
  {
    id: '7',
    name: 'Listmonk',
    description: 'High performance, self-hosted, newsletter and mailing list manager with a modern dashboard.',
    github_url: 'https://github.com/knadh/listmonk',
    saas_equivalent: 'Mailchimp',
    category: 'Marketing',
    stars: 14000,
    last_commit: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 2,
    docker_ready: true,
    created_at: new Date().toISOString(),
    // v2 fields
    license_type: 'AGPL-3.0',
    fork_count: 2800,
    top_contributors: ['knadh:4200', 'mr-karan:380', 'maxking:240'],
    languages: ['Go:420000', 'JavaScript:95000', 'HTML:52000', 'Vue:38000'],
  },
  {
    id: '8',
    name: 'Gitea',
    description: 'Painless self-hosted all-in-one software development service including Git hosting, code review, and CI/CD.',
    github_url: 'https://github.com/go-gitea/gitea',
    saas_equivalent: 'GitHub',
    category: 'DevTools',
    stars: 43000,
    last_commit: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 3,
    docker_ready: true,
    created_at: new Date().toISOString(),
    // v2 fields
    license_type: 'MIT',
    fork_count: 8600,
    top_contributors: ['lunny:7200', 'zeripath:3800', 'techknowlogick:2400', '6543:1950'],
    languages: ['Go:1200000', 'HTML:280000', 'TypeScript:165000', 'JavaScript:95000'],
  },
  {
    id: '9',
    name: 'MinIO',
    description: 'High-performance, S3 compatible object storage. Built for AI/ML, data lakes, and high-performance applications.',
    github_url: 'https://github.com/minio/minio',
    saas_equivalent: 'AWS S3',
    category: 'Storage',
    stars: 45000,
    last_commit: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 4,
    docker_ready: true,
    created_at: new Date().toISOString(),
    // v2 fields
    license_type: 'AGPL-3.0',
    fork_count: 9000,
    top_contributors: ['harshavardhana:12500', 'kannappanr:3200', 'poornas:2800', 'koolhead17:1650'],
    languages: ['Go:1450000', 'Shell:82000', 'Python:45000', 'Makefile:28000'],
  },
  {
    id: '10',
    name: 'Vaultwarden',
    description: 'Unofficial Bitwarden compatible server written in Rust. Lightweight and perfect for self-hosting.',
    github_url: 'https://github.com/dani-garcia/vaultwarden',
    saas_equivalent: 'Bitwarden',
    category: 'Security',
    stars: 35000,
    last_commit: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 2,
    docker_ready: true,
    created_at: new Date().toISOString(),
    // v2 fields
    license_type: 'GPL-3.0',
    fork_count: 7000,
    top_contributors: ['dani-garcia:1850', 'BlackDex:1420', 'jjlin:980'],
    languages: ['Rust:380000', 'HTML:95000', 'JavaScript:42000', 'CSS:18000'],
  },
  {
    id: '11',
    name: 'AFFiNE',
    description: 'The next-gen knowledge base that brings planning, sorting, and creating together. Privacy-focused and local-first.',
    github_url: 'https://github.com/toeverything/AFFiNE',
    saas_equivalent: 'Notion',
    category: 'Project Management',
    stars: 36000,
    last_commit: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 5,
    docker_ready: true,
    created_at: new Date().toISOString(),
    // v2 fields
    license_type: 'MIT',
    fork_count: 7200,
    top_contributors: ['himself65:8500', 'pengx17:3200', 'darkskygit:2100', 'lawvs:1680'],
    languages: ['TypeScript:2100000', 'Rust:320000', 'JavaScript:85000', 'CSS:42000'],
  },
  {
    id: '12',
    name: 'Umami',
    description: 'Simple, fast, privacy-focused alternative to Google Analytics that respects visitor privacy.',
    github_url: 'https://github.com/umami-software/umami',
    saas_equivalent: 'Google Analytics',
    category: 'Analytics',
    stars: 21000,
    last_commit: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    self_host_difficulty: 2,
    docker_ready: true,
    created_at: new Date().toISOString(),
    // v2 fields
    license_type: 'MIT',
    fork_count: 4200,
    top_contributors: ['mikecao:5800', 'briancao:1240', 'gnarlex:680'],
    languages: ['TypeScript:520000', 'JavaScript:125000', 'CSS:38000', 'HTML:22000'],
  },
];
